apiVersion: apps/v1
kind: Deployment
metadata:
  name: webcolor
spec:
  selector:
    matchLabels:
      app: webcolor
  template:
    metadata:
      labels:
        app: webcolor
    spec:
      imagePullSecrets:
      - name: ocirsecret
      containers:
      - name: webcolor
        image: gru.ocir.io/grglog7bpvjm/web-color:blue
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webcolor
spec:
  selector:
    app: webcolor
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer

