apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: exemplo-project
  namespace: argocd
spec:
  description: Projeto de exemplo para a aula de Argocd
  sourceRepos:
  - https://github.com/wesleymlopes/web-color-deploy
  destinations:
  - namespace: web-color
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - kind: 'Namespace'
    group: ''
  namespaceResourceWhitelist:
    - kind: '*'
      group: '*'
  syncWindows:
  - kind: deny
    timeZone: America/Sao_Paulo
    schedule: "* * * * *"
    duration: 2h
    manualSync: true
    applications:
    - web-color
  