apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-color
  namespace: argocd
spec:
  project: exemplo-project
  source:
    repoURL: https://github.com/wesleymlopes/web-color-deploy
    path: k8s_eks
    targetRevision: HEAD
  destination:
    namespace: web-color
    server: https://3905F37C27DFE39CE7CFCD5E11638C54.gr7.us-east-2.eks.amazonaws.com
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
