apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: caos
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/wesleymlopes/web-color-deploy
    path: caos
    targetRevision: HEAD
  destination:
    namespace: caos
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true