apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-color
  namespace: argocd
spec:
  # Vamos definir aqui a fonte do manifesto
  source:
    # Repositório Git
    repoURL: https://github.com/wesleymlopes/web-color-deploy
    # Diretório
    path: k8s
    # Target revision
    targetRevision: HEAD
  # Agora vamos definir o ambiente que vai ser usado
  destination:
    namespace: webcolor
    server: https://kubernetes.default.svc
  # Definindo o projeto (aqui vai ser o default)
  project: default