apiVersion: batch/v1
kind: Job
metadata:
  generateName: pre-sync-
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: chamada
          image: docker.io/curlimages/curl:latest
          command:
            - /bin/sh
            - -c
            - |
              curl -X POST -H "Content-Type: application/json" \
              -d '{"message": "Entrou em Pre Sync !!!"}' \
              https://webhook.site/1bf967db-820c-4c9a-8bcd-1fc457e4160b
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: sync-
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: chamada
          image: docker.io/curlimages/curl:latest
          command:
            - /bin/sh
            - -c
            - |
              curl -X POST -H "Content-Type: application/json" \
              -d '{"message": "Entrou em Sync !!!"}' \
              https://webhook.site/1bf967db-820c-4c9a-8bcd-1fc457e4160b
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: post-sync-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: chamada
          image: docker.io/curlimages/curl:latest
          command:
            - /bin/sh
            - -c
            - |
              curl -X POST -H "Content-Type: application/json" \
              -d '{"message": "Entrou em Post Sync !!!"}' \
              https://webhook.site/1bf967db-820c-4c9a-8bcd-1fc457e4160b
      restartPolicy: Never